extend command line parameters (v0.10.2) better support for scripted cross toolchain creation new commandline options: ./s3 tcupdate TOOLCHAIN-NAME LIBRARY-KEY-1,LIBRARY-KEY-2,LIBRARY-KEY-n #update the specified toolchain with the specified libraries

diff --git a/support/functions/_plugin_update_toolchain b/support/functions/_plugin_update_toolchain
--- a/support/functions/_plugin_update_toolchain
+++ b/support/functions/_plugin_update_toolchain
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 tcupdate(){
-	pversion="0.10.1";
+	pversion="0.10.2";
 	pname="s3.TUP";
 	pdesc="Plugin $pname v$pversion";
 	configname="$configdir/plugin_update_toolchain.config";
@@ -113,139 +113,104 @@ tcupdate(){
 	prefixdir="$PWD"
 	pkg=$(find * | grep -m1 "/pkgconfig") && pkgdir="$prefixdir/$pkg" || pkgdir="$prefixdir";
 	
-	#build menu items from config file
-	unset MENU_OPTIONS;COUNT=0;unset libs;
-	for i in "${LIBS[@]}"
+	backxit=$menu_close;
+	unset menu_close;
+	while [ ! $menu_close ]
 	do
-		[ "${!i}" == "0" ] && continue;
-		libkey=$i;
-		libname="$i"_name;libname=${!libname};
-		libdesc="$i"_desc;libdesc=${!libdesc};
-		libversion="$i"_version;libversion=${!libversion};
-		libcheck="$i"_check;libcheck=${!libcheck};
-		libversioncheck=$(echo "$libcheck" | awk '{printf $2}')
-		libcheck=$(echo "$libcheck" | awk '{printf $1}')
-		liburl="$i"_url;liburl=${!liburl};
-		libversioncurrent=$(_get_version "$pkgdir/$libcheck" "$libversioncheck");
-		libversioncompare=$(_compare_version $libversion $(echo $libversioncurrent | sed -e 's/^$/0.0.0/g'));
-		libtasks="$i"_tasks[@];libtasks=("${!libtasks}");
-		libexports="$i"_exports[@];libexports=("${!libexports}");
-		libconfigure="$i"_configure[@];libconfigure=("${!libconfigure}");
-		libmake="$i"_make[@];libmake=("${!libmake}");
+		cd "$prefixdir"
+		#build menu items from config file
+		unset MENU_OPTIONS;COUNT=0;unset libs;
+		for i in "${LIBS[@]}"
+		do
+			[ "${!i}" == "0" ] && continue;
+			libkey=$i;
+			libname="$i"_name;libname=${!libname};
+			libdesc="$i"_desc;libdesc=${!libdesc};
+			libversion="$i"_version;libversion=${!libversion};
+			libcheck="$i"_check;libcheck=${!libcheck};
+			libversioncheck=$(echo "$libcheck" | awk '{printf $2}')
+			libcheck=$(echo "$libcheck" | awk '{printf $1}')
+			liburl="$i"_url;liburl=${!liburl};
+			libversioncurrent=$(_get_version "$pkgdir/$libcheck" "$libversioncheck");
+			libversioncompare=$(_compare_version $libversion $(echo $libversioncurrent | sed -e 's/^$/0.0.0/g'));
+			libtasks="$i"_tasks[@];libtasks=("${!libtasks}");
+			libexports="$i"_exports[@];libexports=("${!libexports}");
+			libconfigure="$i"_configure[@];libconfigure=("${!libconfigure}");
+			libmake="$i"_make[@];libmake=("${!libmake}");
 
-		MENU_OPTIONS+=("$i"		"$libname $libversion  	$([ $libversioncurrent ] && echo $libversioncompare)	$(echo $libversioncurrent | sed -e 's/^$/ ---/g')"		"$([ $libversioncurrent ] && echo "on" || echo "off")"	"$([ $libname ] && echo "$libname $libversion: $liburl")");counter;
-		
-		#     0 key     1 desc     2 version     3 checkversion     4 checkfile 5 current version    6 url      7 tasks array
-		lib=("$libkey" "$libname" "$libversion" "$libversioncheck" "$libcheck" "$libversioncurrent" "$liburl" "(${libtasks[*]@Q})");
-		libs+=("(${lib[*]@Q})");
-	done;
-	[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no libraries found" "no libraries found") && counter;
-
-	opts=$("$gui" "--item-help" "--help-tags" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--default-item" "$3" "--ok-label" "Start" "--help-button" "--help-label" "Info" "--cancel-label" "$([ "$menu_close" == "1" ] && echo "Back" || echo "Exit")" "--title" "-[ Library Update Menu - \Z2$tc\Zn ]-" "$cl_"\
-		"\nSelect all libraries to update in toolchain's SYSROOT folder:\n$prefixdir\n\n       library version    NEW                    CURRENT" \
-		"${COUNT+12}" 70 0 "${MENU_OPTIONS[@]}");
-	
-	#SSL select check
-	[ $(echo $opts | tr ' ' '\n' | grep -c "SSL_") -gt 1 ] && echo -e $r_l"\n\nPlease select only one SSL version!"$re_ && sleep 3 && tcupdate $tc;
-	
-	#HELP section
-	first=$(echo "$opts" | awk '{printf $1}');
-	libkey=$(echo "$opts" | awk '{printf $2}';);
-
-	if [ "$first" == "HELP" ];then
-		sp=$(printf '%*s' 90 | tr ' ' '=');
-		txt=$(cat "$configname" | grep ""$libkey"=\|"$libkey"_");
-		bcd=$(cat "$configname" | grep ""$libkey"_tasks");
-		txt=$(echo -e "Toolchain: $tcdir/$tc\nCompiler:  $compilername\nSysroot:   $sr\nPrefix:    $prefixdir\nInclude:   $incdir\n$sp\n\nLibrary configuration:\n$txt\n\nBuild command:\n$(_replace_tokens "$(_tidy_tasks "$bcd" "$libkey")")");
-		tempfile=$(mktemp) && echo -e "$txt" > "$tempfile";
-		"$gui" "$st_" "$nc_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--textbox" "$tempfile" 30 80;
-		rm "$tempfile" 2>/dev/null;
-		tcupdate $tc $tc_menu $libkey;
-	fi;	
-
-	#BUILD library section
-	ts=$(date +%F)_$(date +%T);
-	tmpdir="/tmp/lib_source/$ts";
-	icount=$(echo $opts | wc -w);i=0;
-	for o in $opts;do
-		unset buildtasks;
-		for l in "${libs[@]}";do
-			declare -a lib="${l[*]}";				#populate libs array element
-			[ ! "$o" == "${lib[0]}" ] && continue || ((i++));
-			logfile="$ldir/"$ts"_update_toolchain_"$_toolchainname"_"${lib[1]}"_"${lib[2]}".log"
-
-			#generate build command list
-			declare -a libtasks="${lib[7]}";		#populate tasks array element
-			for task in "${libtasks[@]}";do
-				task=$(_replace_tokens "$task");	#replace tokens
-				buildtasks+=("$task");
-			done
-			_build "($i/$icount) $tc: library ${lib[1]} ${lib[2]}" $(_extract $(_dl "${lib[6]}" "${lib[1]} ${lib[2]}") "$tmpdir") "$logfile" "${buildtasks[@]}";
+			MENU_OPTIONS+=("$i"		"$libname $libversion  	$([ $libversioncurrent ] && echo $libversioncompare)	$(echo $libversioncurrent | sed -e 's/^$/ ---/g')"		"$([ $libversioncurrent ] && echo "on" || echo "off")"	"$([ $libname ] && echo "$libname $libversion: $liburl")");counter;
+			
+			#     0 key     1 desc     2 version     3 checkversion     4 checkfile 5 current version    6 url      7 tasks array
+			lib=("$libkey" "$libname" "$libversion" "$libversioncheck" "$libcheck" "$libversioncurrent" "$liburl" "(${libtasks[*]@Q})");
+			libs+=("(${lib[*]@Q})");
 		done;
-	done;
-	[ -d "$tmpdir" ] && rm -r "$tmpdir";
-	
-	#Reopen update menu
-	if [ ${#opts} -gt 0 ];then
-		tcupdate "$tc" "$OPTION1" "$OPTION2" "$menu_close";
-	else
-		[ "$menu_close" == "1" ] && tcupdate "" "$OPTION1" "$OPTION2" "$FLAG" || bye;
-	fi;
-};
-_select_tc(){
-	_fill_tc_array;
-	unset MENU_OPTIONS;COUNT=0
-	if [ "$systype" == "ok" ];then
-		if [ "$tcempty" == "0" ];then
-			for i in "${INST_TCLIST[@]}";do
-				if [ ! "$i" == "native" ];then
-					source "$tccfgdir/$i";
-					[ -f "$tcdir/$i/build.log.bz2" ] && tcdate=" ct-ng."$(date -r "$tcdir/$i/build.log.bz2" "+%Y-%m-%d %H:%M:%S") || tcdate="";
-					MENU_OPTIONS+=("$_toolchainname" "$_description\Z2$tcdate\Zn" "toolchain folder:$tcdir/$i | config file:$tccfgdir/$i");
-					counter;
-				fi;
-			done;
+		[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no libraries found" "no libraries found") && counter;
+
+		if [ ${#OPTION1} -gt 0 ];then #Force build library call
+			opts=$(echo "$OPTION1" | tr ',' "\n");
+			ret="0";
+		else
+			clear;clear;
+			opts=$("$gui" "--item-help" "--help-tags" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--default-item" "$lkey" "--ok-label" "Start" "--help-button" "--help-label" "Info" "--cancel-label" "$([ "$backxit" == "1" ] && echo "Back" || echo "Exit")" "--title" "-[ Library Update Menu - \Z2$tc\Zn ]-" "$cl_"\
+				"\nSelect all libraries to update in toolchain's SYSROOT folder:\n$prefixdir\n\n       library version    NEW                    CURRENT" \
+				"${COUNT+12}" 70 0 "${MENU_OPTIONS[@]}");
+			ret="$?"
 		fi;
-		[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no toolchains found" "no toolchains found") && counter;
-	fi;
-	
-	out=$("$gui" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--item-help" "--help-tags" "--default-item" "$1" "--ok-label" "Update" "--cancel-label" "Create" "--help-button" "--help-label" "$([ "$2" == "1" ] && echo "Exit" || echo "Back")" "--extra-button" "--extra-label" "Backup" "--title" "-[ Toolchain Menu ]-" \
-		--menu "\nSelect one of the installed tool chains that you want to update:\n " \
-		"${COUNT+10}" 0 0 "${MENU_OPTIONS[@]}");
-	ret="$?"
-	tc=$(echo "$out" | awk '{printf $1}');
-	echo "$tc";
-	return $ret;
-};
-_select_tpl(){
-	tplempty=0;
-	[ ! -d "$cttpldir" ] && mkdir --parents "$cttpldir";
-	cd "$cttpldir";
 
-	if [ "$(ls -A "$cttpldir")" ];then
-		TPL_LIST=(*);
+		#SSL select check
+		[ $(echo $opts | tr ' ' '\n' | grep -c "SSL_") -gt 1 ] && echo -e $r_l"\n\nPlease select only one SSL version!"$re_ && sleep 3 && [ ${#OPTION1} -gt 0 ] && menu_close=1 && continue;
+
+		case $ret in
+			0) #Start - Build library
+				ts=$(date +%F)_$(date +%T);
+				tmpdir="/tmp/lib_source/$ts";
+				icount=$(echo $opts | wc -w);i=0;
+				for o in $opts;do
+					unset buildtasks;
+					for l in "${libs[@]}";do
+						declare -a lib="${l[*]}";				#populate libs array element
+						[ ! "$o" == "${lib[0]}" ] && continue || ((i++));
+						logfile="$ldir/"$ts"_update_toolchain_"$_toolchainname"_"${lib[1]}"_"${lib[2]}".log"
+
+						#generate build command list
+						declare -a libtasks="${lib[7]}";		#populate tasks array element
+						for task in "${libtasks[@]}";do
+							task=$(_replace_tokens "$task");	#replace tokens
+							buildtasks+=("$task");
+						done
+						_build "($i/$icount) $tc: library ${lib[1]} ${lib[2]}" $(_extract $(_dl "${lib[6]}" "${lib[1]} ${lib[2]}") "$tmpdir" 2>/dev/null) "$logfile" "${buildtasks[@]}";
+					done;
+					[ "${#buildtasks[@]}" == "0" ] && echo -e "$r_l  $txt_error:$y_l $o$w_l Library not found in config file""$rs_";
+				done;
+				[ -d "$tmpdir" ] && rm -r "$tmpdir";;
+			1) #Exit/Back
+				menu_close="1";;
+			2) #Info
+				first=$(echo "$opts" | awk '{printf $1}');
+				lkey=$(echo "$opts" | awk '{printf $2}';);
+
+				if [ "$first" == "HELP" ];then
+					sp=$(printf '%*s' 90 | tr ' ' '=');
+					txt=$(cat "$configname" | grep ""$lkey"=\|"$lkey"_");
+					bcd=$(cat "$configname" | grep ""$lkey"_tasks");
+					txt=$(echo -e "Toolchain: $tcdir/$tc\nCompiler:  $compilername\nSysroot:   $sr\nPrefix:    $prefixdir\nInclude:   $incdir\n$sp\n\nLibrary configuration:\n$txt\n\nBuild command:\n$(_replace_tokens "$(_tidy_tasks "$bcd" "$lkey")")");
+					tempfile=$(mktemp) && echo -e "$txt" > "$tempfile";
+					"$gui" "$st_" "$nc_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--ok-label" "Back" "--textbox" "$tempfile" 30 80;
+					rm "$tempfile" 2>/dev/null;
+				fi;;
+		esac;
+		
+		#Exit loop if build library is forced
+		[ ${#OPTION1} -gt 0 ] && menu_close=1;
+	done;
+	
+	#Reopen previous menu
+	[ ${#OPTION1} -gt 0 ] && exit;
+	if [ ${#opts} -gt 0 ];then
+		tcupdate "$tc" "$OPTION1" "$OPTION2" "$backxit";
 	else
-		tplempty=1;
+		[ "$backxit" == "1" ] && tcupdate "" "$OPTION1" "$OPTION2" "$FLAG" || bye;
 	fi;
-
-	unset MENU_OPTIONS;COUNT=0;
-	if [ "$tplempty" == "0" ];then
-		for t in "${TPL_LIST[@]}";do
-			desc=$(sed -n -e '/#toolchain template/ s/.*\: *//p' $t);
-			[ ! "$desc" ] && desc="no description available";
-			[ -d "$tcdir/$t" ] && [ -f "$tccfgdir/$t" ] && color="\Z1" || color="";
-			MENU_OPTIONS+=("$t" "$color$desc\Zn" "off" "template filename:$cttpldir/$t");counter;
-			counter;
-		done;
-	fi;
-	[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no templates found" "no templates found") && counter;
-	
-	opts=$("$gui" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--item-help" "--help-tags" "--default-item" "$1" "--ok-label" "Start" "--cancel-label" "Setup" "--help-button" "--help-label" "$([ $2 == "1" ] && echo "Exit" || echo "Back")" "--title" "-[ Cross Toolchain Template Menu ]-" "$cl_"\
-		 "\nSelect on of the templates to create the cross toolchain you want:\n\n\Z1NOTE: If you create a cross toolchain from a template with a red colored description, an existing one with the same name will be replaced without asking!\Zn" \
-		 "${COUNT+11}" 0 0 "${MENU_OPTIONS[@]}");
-	ret="$?"
-	echo "$opts";
-	return $ret;
 };
 _create_tc(){
 	_sz;					# Prepare DIALOG settings
@@ -377,6 +342,62 @@ _create_tc(){
 		
 	done;
 };
+_select_tc(){
+	_fill_tc_array;
+	unset MENU_OPTIONS;COUNT=0
+	if [ "$systype" == "ok" ];then
+		if [ "$tcempty" == "0" ];then
+			for i in "${INST_TCLIST[@]}";do
+				if [ ! "$i" == "native" ];then
+					source "$tccfgdir/$i";
+					[ -f "$tcdir/$i/build.log.bz2" ] && tcdate=" ct-ng."$(date -r "$tcdir/$i/build.log.bz2" "+%Y-%m-%d %H:%M:%S") || tcdate="";
+					MENU_OPTIONS+=("$_toolchainname" "$_description\Z2$tcdate\Zn" "toolchain folder:$tcdir/$i | config file:$tccfgdir/$i");
+					counter;
+				fi;
+			done;
+		fi;
+		[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no toolchains found" "no toolchains found") && counter;
+	fi;
+	clear;clear;
+	out=$("$gui" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--item-help" "--help-tags" "--default-item" "$1" "--ok-label" "Update" "--cancel-label" "Create" "--help-button" "--help-label" "$([ "$2" == "1" ] && echo "Exit" || echo "Back")" "--extra-button" "--extra-label" "Backup" "--title" "-[ Toolchain Menu ]-" \
+		--menu "\nSelect one of the installed tool chains that you want to update:\n " \
+		"${COUNT+10}" 0 0 "${MENU_OPTIONS[@]}");
+	ret="$?"
+	tc=$(echo "$out" | awk '{printf $1}');
+	echo "$tc";
+	return $ret;
+};
+_select_tpl(){
+	tplempty=0;
+	[ ! -d "$cttpldir" ] && mkdir --parents "$cttpldir";
+	cd "$cttpldir";
+
+	if [ "$(ls -A "$cttpldir")" ];then
+		TPL_LIST=(*);
+	else
+		tplempty=1;
+	fi;
+
+	unset MENU_OPTIONS;COUNT=0;
+	if [ "$tplempty" == "0" ];then
+		for t in "${TPL_LIST[@]}";do
+			desc=$(sed -n -e '/#toolchain template/ s/.*\: *//p' $t);
+			[ ! "$desc" ] && desc="no description available";
+			[ -d "$tcdir/$t" ] && [ -f "$tccfgdir/$t" ] && color="\Z1" || color="";
+			MENU_OPTIONS+=("$t" "$color$desc\Zn" "off" "template filename:$cttpldir/$t");counter;
+			counter;
+		done;
+	fi;
+	
+	[ $COUNT -eq 0 ] && MENU_OPTIONS+=("" "no templates found" "no templates found") && counter;
+	clear;clear;
+	opts=$("$gui" "$st_" "$bt_" "$title_ - \Z0$pdesc\Zn" "--colors" "--item-help" "--help-tags" "--default-item" "$1" "--ok-label" "Start" "--cancel-label" "Setup" "--help-button" "--help-label" "$([ "$2" == "1" ] && echo "Exit" || echo "Back")" "--title" "-[ Cross Toolchain Template Menu ]-" "$cl_"\
+		 "\nSelect on of the templates to create the cross toolchain you want:\n\n\Z1NOTE: If you create a cross toolchain from a template with a red colored description, an existing one with the same name will be replaced without asking!\Zn" \
+		 "${COUNT+11}" 0 0 "${MENU_OPTIONS[@]}");
+	ret="$?"
+	echo "$opts";
+	return $ret;
+};
 _backup(){
 
 	_sz;					# Prepare DIALOG settings
@@ -396,7 +417,6 @@ _backup(){
 	[ -f "$newtccfgfile" ] && echo "$dest";
 };
 _build(){
-	
 	_sz;					# Prepare DIALOG settings
 	local desc="$1";		# Save 1. argument in a variable
 	local libsrcdir="$2";	# Save 2. argument in a variable
